version: '3.2'
services:
  db:
    image: postgres
    volumes:
      - db_datavolume:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "443:3000"
    depends_on:
      - db
    command: passenger start
volumes:
  db_datavolume:
