version: '3.2'
services:
  db:
    image: postgres

  web:
    build: .
    volumes:
      #      - .:/myapp
      #      - /bundle
      #- type: bind
      #  source: .
      #  target: /myapp
      - .:/myapp
      - type: volume
        source: bundle
        target: /bundle
        volume: 
          nocopy: true

    ports:
      - "3000:3000"
    depends_on:
      - db
      - bundle 
      - webpack-dev
    command: ./bin/rails s -p 3000 -b '0.0.0.0' 
    tty: true
    stdin_open: true

  webpack-dev:
    image: honey_do_web
    build:
      context: .
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    volumes:
      - .:/myapp
    command: ./bin/webpack-dev-server --inline true --hot true --port 8080 --public localhost:8080

  bundle:
    image: honey_do_web
    command: echo bundling ruby gems??
    volumes:
      - type: volume
        source: bundle
        target: /bundle


#  node_modules:
#    image: honey_do_web
#    command: echo building node modules??
#    volumes: 
#      - /node_modules

volumes: 
  bundle:
