version: '3.2'
services:
  db:
    image: postgres
  volumes:
    - db_datavolume:/var/lib/postgresql/data 

  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    #command: ./bin/rails s -p 3000 -b '0.0.0.0'
    command: passenger start
    tty: true
    stdin_open: true
