development: &default
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: postgres
  host: db

test:
  <<: *default
  database: myapp_test

#production:
#  <<: *default
#  host: <%= ENV['DATABASE_URL'] %>

# For production running on Amazon Elastic Beanstalk
production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
